server.port=8060

# routes:
# route user-service
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.name=userServiceCB
spring.cloud.gateway.routes[0].filters[0].args.fallbackUri=forward:/api/fallback/user-service
# route notification-service
spring.cloud.gateway.routes[1].id=notification-service
spring.cloud.gateway.routes[1].uri=lb://notification-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/notifications/**
spring.cloud.gateway.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[1].filters[0].args.name=notificationServiceCB
spring.cloud.gateway.routes[1].filters[0].args.fallbackUri=forward:/api/fallback/notification-service

# configuration Gateway
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Circuit Breaker
resilience4j.timelimiter.instances.userServiceCB.timeout-duration=2s
resilience4j.circuitbreaker.instances.userServiceCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.userServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userServiceCB.wait-duration-in-open-state=10s